# Generated by Django 4.0.1 on 2022-02-04 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainingwellapi', '0002_exercisetype_exercise_benchmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingwellapi.account')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField()),
                ('notes', models.CharField(max_length=250)),
                ('sleep_hours', models.IntegerField(null=True)),
                ('energy_level', models.IntegerField(null=True)),
                ('quality', models.IntegerField(null=True)),
                ('training_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingwellapi.trainingplan')),
            ],
        ),
        migrations.CreateModel(
            name='LoggedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=250)),
                ('completed', models.BooleanField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingwellapi.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingwellapi.session')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('goal_achieved', models.BooleanField()),
                ('training_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingwellapi.trainingplan')),
            ],
        ),
    ]
