# Generated by Django 4.0.1 on 2022-02-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingwellapi', '0004_session_time_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedexercise',
            name='reps',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loggedexercise',
            name='sets',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loggedexercise',
            name='weight_used',
            field=models.IntegerField(null=True),
        ),
    ]
