# Generated by Django 4.0.1 on 2022-02-08 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainingwellapi', '0005_loggedexercise_reps_loggedexercise_sets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='training_plan',
        ),
        migrations.RemoveField(
            model_name='session',
            name='training_plan',
        ),
        migrations.AddField(
            model_name='goal',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trainingwellapi.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trainingwellapi.account'),
            preserve_default=False,
        ),
    ]
