# Generated by Django 4.0.1 on 2022-02-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingwellapi', '0006_remove_goal_training_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedexercise',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
