# Generated by Django 4.0.1 on 2022-02-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingwellapi', '0007_loggedexercise_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_coach',
            field=models.BooleanField(default=False),
        ),
    ]
