# Generated by Django 4.0.1 on 2022-02-18 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainingwellapi', '0008_alter_account_is_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_coaching_request', models.BooleanField(default=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach', to='trainingwellapi.account')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingwellapi.account')),
            ],
        ),
    ]
